# GitHub Actions CI workflow for Zip Ride Project
name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'

    - name: Install backend dependencies
      run: |
        cd test/backend
        npm install

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Check Python and pip
      run: |
        python --version
        pip install --upgrade pip

    # (Optional) Add your backend tests here
    # - name: Run backend tests
    #   run: |
    #     cd test/backend
    #     npm test

    # (Optional) Add your frontend build/test steps here

    - name: Finish
      run: echo "Pipeline completed!"
